name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: action-slack
      uses: 8398a7/action-slack@v3.12.0
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
      
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download dependences swag
      run: go get -u github.com/swaggo/swag/cmd/swag

    - name: Download dependences
      run: go mod download

    - name: Set up Swag Docs
      run: swag init

    - name: Build
      run: CGO_ENABLED=1 go build -ldflags="-w -s" -v .

    - name: Test
      run: go test -v ./...
